Test branch
emiliocm9/Enumerable_Methods-Project pull request #2
Opened 2020-06-22 20:06 UTC by santiagorodriguezbermudez

# Test Branch Request

## In this branch we worked on:
- [x] Added RSpec methods to test:
- my_each
- my_each_with_index
- my_select
- my_any?
- my_all?
- my_none?
- my_count
- my_map
- my_inject

2020-06-22 20:59 UTC, kobiyoyo requested changes
## Hi Team     ![](https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png) 
#### Great Job so far, but there are a few more things required. 
### General
 - [x] Lets edit this pull request, you are to use Gitflow for this project  
 - [x] The readme file should be descriptive, for example how to run test, how to clone this project should be included.  
 - [x] Check comments below
### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

2020-06-22 20:59 UTC, kobiyoyo commented on spec/enumerable_spec.rb
> +  end
Test for when
- [ ] when a class is passed as an argument.
- [ ] when no block or argument is given

2020-06-22 20:59 UTC, kobiyoyo commented on spec/enumerable_spec.rb
> +  end
Test for when
- [ ] when a class is passed as an argument.
- [ ] when no block or argument is given

2020-06-22 20:59 UTC, kobiyoyo commented on spec/enumerable_spec.rb
> +  end
Test for when
- [ ] when a class is passed as an argument.
- [ ] when no block or argument is given

2020-06-22 20:59 UTC, kobiyoyo commented on spec/enumerable_spec.rb
> +  end
Test for when
- [ ] when no block or argument is given

2020-06-22 23:51 UTC, santiagorodriguezbermudez commented
## Code Review # 1

We made the following changes:
- [x] Rebase the pull request to merge into develop branch
- [x] Implemented new scenarios in my_any?, my_all?, my_none? and my_map? according to the TSE suggestions. 
- [x] Wrote Readme instructions to run tests.

2020-06-23 00:20 UTC, lekegitrepo commented
#### Good job :clap: :clap:
#### Well done for implementing the required changes. This project is approved.

#### _Reviewed by Temitayo Adeleke_.

2020-06-23 00:21 UTC, lekegitrepo approved these changes
#### Status: Approved.

2020-06-23 14:40 UTC, merged